syntax = "proto3";

package passmanager.user.v0;

import "passmanager/common/v0/error.proto";
import "passmanager/common/v0/secure.proto";

service User {
  rpc Register (UserRegisterRequest) returns (UserRegisterResponse);
  rpc Username (passmanager.common.v0.SecureRequest) returns (passmanager.common.v0.SecureResponse);
  rpc Delete (passmanager.common.v0.SecureRequest) returns (passmanager.common.v0.SecureResponse);
  rpc Health (passmanager.common.v0.HealthRequest) returns (passmanager.common.v0.HealthResponse);
}

message UserRegisterRequest {
  bytes new_username = 1;
  bytes srp_salt = 2;
  bytes srp_verifier = 3;
  bytes master_key_salt = 4;
}

message UserRegisterResponse {
  bool success = 1;

  oneof result {
    Success success_data = 2;
    passmanager.common.v0.Failure failure_data = 3;
  }

  message Success {
    bytes username_hash = 1;
  }
}
