syntax = "proto3";

package passmanager.password.v0;

import "passmanager/common/v0/error.proto";
import "passmanager/common/v0/secure.proto";

message Failure = passmanager.common.v0.Failure
message SecureRequest = passmanager.common.v0.SecureRequest;
message SecureResponse = passmanager.common.v0.SecureResponse;

service Password {
  rpc Start (SecureRequest) returns (SecureResponse);
  rpc Auth (SecureRequest) returns (SecureResponse);
  rpc Complete (SecureRequest) returns (SecureResponse);
  rpc Abort (SecureRequest) returns (SecureResponse);
  rpc Get (SecureRequest) returns (SecureResponse);
  rpc Update (SecureRequest) returns (SecureResponse);
}
