syntax = "proto3";

package passmanager.password.v0;

message PasswordStartRequest {
  bytes username_hash = 1;
  bytes srp_salt = 2;
  bytes srp_verifier = 3;
  bytes master_key_salt = 4;
}

message PasswordStartResponse {
  bytes username_hash = 1;
  string public_id = 2;
  bytes eph_public_b = 3;
  bytes srp_salt = 4;
  bytes master_key_salt = 5;
}

message PasswordAuthRequest {
  bytes username_hash = 1;
  string public_id = 2;
  bytes eph_val_a = 3;
  bytes proof_val_m1 = 4;
}

message PasswordAuthResponse {
  bytes username_hash = 1;
  string session_id = 2;
  bytes server_proof_m2 = 3;
  repeated string public_ids = 4;
}

message PasswordCommitRequest {
  bytes username_hash = 1;
}

message PasswordCommitResponse {
  bytes username_hash = 1;
}

message PasswordAbortRequest {
  bytes username_hash = 1;
}

message PasswordAbortResponse {
  bytes username_hash = 1;
}

message PasswordGetRequest {
  bytes username_hash = 1;
  string public_id = 2;
}

message PasswordGetResponse {
  bytes username_hash = 1;
  string public_id = 2;
  bytes entry_name = 3;
  bytes entry_data = 4;
}

message PasswordUpdateRequest {
  bytes username_hash = 1;
  string public_id = 2;
  bytes entry_name = 3;
  bytes entry_data = 4;
}

message PasswordUpdateResponse {
  bytes username_hash = 1;
  string public_id = 2;
}
