syntax = "proto3";

package passmanager.password.v0;

import "passmanager/common/v0/error.proto";
import "passmanager/common/v0/session.proto";

message Failure = passmanager.common.v0.Failure
message SessionRequest = passmanager.common.v0.SessionRequest;
message SessionResponse = passmanager.common.v0.SessionResponse;

service Password {
    rpc Start (SessionRequest) returns (SessionResponse);
    rpc Auth  (SessionRequest) returns (SessionResponse);
    rpc Complete (SessionRequest) returns (SessionResponse);
    rpc Abort (SessionRequest) returns (SessionResponse);
    rpc Get (SessionRequest) returns (SessionResponse);
    rpc Update (SessionRequest) returns (SessionResponse);
}
