syntax = "proto3";

package passmanager.password.v0;

import "passmanager/common/v0/error.proto";
import "passmanager/common/v0/secure.proto";

service Password {
  rpc Start (passmanager.common.v0.SecureRequest) returns (passmanager.common.v0.SecureResponse);
  rpc Auth (passmanager.common.v0.SecureRequest) returns (passmanager.common.v0.SecureResponse);
  rpc Complete (passmanager.common.v0.SecureRequest) returns (passmanager.common.v0.SecureResponse);
  rpc Abort (passmanager.common.v0.SecureRequest) returns (passmanager.common.v0.SecureResponse);
  rpc Get (passmanager.common.v0.SecureRequest) returns (passmanager.common.v0.SecureResponse);
  rpc Update (passmanager.common.v0.SecureRequest) returns (passmanager.common.v0.SecureResponse);
  rpc Health (passmanager.common.v0.HealthRequest) returns (passmanager.common.v0.HealthResponse);
}
